### ISSUE TITLE
백준...

### ISSUE THREAD

**Issue by Sam1000won** [tjkpolisher/Baekjoon#2]
크롬확장 드라이버... 
https://oliviakim.tistory.com/34 이거보고 참고해줭..
코드는 상관없는데 문제가 뭔지...
흐에엥

**Comment by tjkpolisher** [comment]
문제 풀고 자동으로 커밋시킬 리포지터리는 만들어 놓은 거야?

**Comment by Sam1000won** [comment]
> 문제 풀고 자동으로 커밋시킬 리포지터리는 만들어 놓은 거야?

??? 형이 이건 안해놓은거 아님?

**Comment by tjkpolisher** [comment]
[다른 리포지터리](https://github.com/tjkpolisher/codingTestTheories)에 걸어놨지

**Comment by Sam1000won** [comment]
> [다른 리포지터리](https://github.com/tjkpolisher/codingTestTheories)에 걸어놨지

화긴.. 
![image](https://github.com/user-attachments/assets/74400643-31c1-43b3-b17f-7bb3ab98079e)
